### ISSUE TITLE
[Question] Automerge changes from `release/*` to `master`

### ISSUE THREAD

**Issue by jeffchew** [Logerfo/gitflow-action#17]
I'm new with setting up Github actions. I'd like to set up a flow where any changes to `release/*` gets merged down to `master` automatically. Would this configuration work with your action:

```yml
name: Gitflow
on: 
  push:
  pull_request_review:
  check_run:
    types: [completed]

jobs:
  build:
    name: Gitflow
    runs-on: ubuntu-16.04
    steps:
    - uses: Logerfo/gitflow-action@0.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release: release/*
        master: master
        label: gitflow
        auto-merge: true
        require-merge: false
```
